name: Bump version
on:
  push:
    branches:
      - develop
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 21
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Bump version
        run: npm version
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
